import { cyaniteGraphQL, sendJson, methodNotAllowed } from "./_cyanite.js";
import { authorityForCandidate, authorityGenres } from "./_authority.js";

const ANALYSIS_QUERY=`query($trackId:ID!){libraryTrack(id:$trackId){__typename ... on LibraryTrackNotFoundError{message} ... on LibraryTrack{id title audioAnalysisV7{__typename ... on AudioAnalysisV7Finished{result{bpmPrediction{value confidence} keyPrediction{value confidence} timeSignature genreTags subgenreTags moodTags moodAdvancedTags instrumentTags movementTags characterTags valence arousal transformerCaption freeGenreTags}} ... on AudioAnalysisV7Failed{error{message}}}}}}`;
const SIMILAR_QUERY=`query($trackId:ID!){libraryTrack(id:$trackId){__typename ... on LibraryTrack{id title similarTracks(target:{spotify:{}},searchMode:{complete:true},first:100){__typename ... on SimilarTracksError{code message} ... on SimilarTracksConnection{edges{node{id title}}}}}}}`;
const FILTERED_SIMILAR_QUERY=`query($trackId:ID!){libraryTrack(id:$trackId){__typename ... on LibraryTrack{similarTracks(target:{spotify:{}},searchMode:{complete:true},first:100,experimental_filter:{bpm:{input:{}},genre:{input:{}}}){__typename ... on SimilarTracksError{code message} ... on SimilarTracksConnection{edges{node{id title}}}}}}}`;
const REPRESENTATIVE_QUERY=`query($trackId:ID!){libraryTrack(id:$trackId){__typename ... on LibraryTrack{similarTracks(target:{spotify:{}},searchMode:{mostRepresentative:true},first:100){__typename ... on SimilarTracksError{code message} ... on SimilarTracksConnection{edges{node{id title}}}}}}}`;

const TECHNICAL=new Set(["final","master","mastered","mix","mixed","mixdown","rough","demo","bounce","export","preview","version","ver","rev","revision","edit","radio","instrumental","client","cliente","fortissimo","analysis"]);
const edgesOf=r=>r?.__typename==="SimilarTracksConnection"?(r.edges||[]):[];
const unique=(v,m=6)=>[...new Set((v||[]).filter(Boolean))].slice(0,m);
function makeDNA(r){return{bpm:r?.bpmPrediction?.value?Math.round(r.bpmPrediction.value):null,bpmConfidence:r?.bpmPrediction?.confidence??null,key:r?.keyPrediction?.value||null,keyConfidence:r?.keyPrediction?.confidence??null,timeSignature:r?.timeSignature||null,genres:unique(r?.genreTags),subgenres:unique(r?.subgenreTags),moods:unique([...(r?.moodAdvancedTags||[]),...(r?.moodTags||[])]),instruments:unique(r?.instrumentTags,8),movement:unique(r?.movementTags),character:unique(r?.characterTags),valence:r?.valence??null,arousal:r?.arousal??null,caption:r?.transformerCaption||null,freeGenre:r?.freeGenreTags||null};}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\.[a-z0-9]{2,5}$/i,"").toLowerCase().replace(/\b(v|ver|version|rev)\s*\d+(?:\.\d+)?\b/g," ").replace(/[^a-z0-9áéíóúñü]+/gi," ").split(/\s+/).filter(w=>w&&!TECHNICAL.has(w)).join(" ").trim();}
function toks(v){return new Set(norm(v).split(/\s+/).filter(x=>x.length>1));}
function overlap(a,b){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size);}
function sameSong(a,b){const A=[String(a||"").replace(/\.[^.]+$/,"")].flatMap(x=>[x,...x.split(/\s[-–—]\s|\s+x\s+/i)]).map(norm).filter(Boolean);const B=[String(b||"")].flatMap(x=>[x,...x.split(/\s[-–—]\s|\s+x\s+/i)]).map(norm).filter(Boolean);return A.some(x=>x.length>=4&&B.some(y=>y.length>=4&&(x===y||(Math.min(x.length,y.length)>=7&&(x.includes(y)||y.includes(x)))||(overlap(x,y)>=.85&&Math.min(toks(x).size,toks(y).size)>=2))));}

function rank(groups,dna,{sourceTitle="",excludeSpotifyId=""}={}){
 const scores=new Map(),tracks=new Map(),K=60;
 for(const {edges,weight,label} of groups) edges.forEach((e,i)=>{const n=e?.node;if(!n?.id||n.id===excludeSpotifyId||sameSong(sourceTitle,n.title))return;tracks.set(n.id,n);const x=scores.get(n.id)||{similarity:0,sources:[]};x.similarity+=weight/(K+i+1);if(!x.sources.includes(label))x.sources.push(label);scores.set(n.id,x);});
 let rows=[...scores].map(([id,x])=>({id,...tracks.get(id),...x,authority:authorityForCandidate(tracks.get(id)?.title,dna)}));
 const maxSim=Math.max(...rows.map(x=>x.similarity),1e-9);
 rows=rows.map(x=>{const acoustic=x.similarity/maxSim;const authority=x.authority.score;return{...x,acoustic,referenceScore:acoustic*.75+authority*.25};});
 // A/B references are preferred. Unknowns remain fallback so acoustic quality is never destroyed by the gate.
 const strong=rows.filter(x=>x.authority.tier==="A"||x.authority.tier==="B").sort((a,b)=>b.referenceScore-a.referenceScore);
 const fallback=rows.filter(x=>x.authority.tier==="C").sort((a,b)=>b.acoustic-a.acoustic);
 const chosen=[...strong,...fallback].slice(0,4);
 return chosen.map((x,i)=>({id:x.id,title:x.title||"Spotify reference",spotifyUrl:`https://open.spotify.com/track/${encodeURIComponent(x.id)}`,matchScore:Math.max(70,Math.min(98,Math.round(70+x.acoustic*28-i))),rank:i+1,signals:x.sources,authorityTier:x.authority.tier,authorityArtist:x.authority.artist,authorityGenre:x.authority.genre,proReference:x.authority.tier==="A",referenceScore:Math.round(x.referenceScore*100)}));
}
async function safe(q,id){try{const d=await cyaniteGraphQL(q,{trackId:id});return edgesOf(d?.libraryTrack?.similarTracks);}catch(e){console.warn("[reference-finder] optional lane skipped",e.message);return[];}}
export default async function handler(req,res){
 if(req.method!=="GET")return methodNotAllowed(res,["GET"]);const trackId=String(req.query?.trackId||""),excludeSpotifyId=String(req.query?.excludeSpotifyId||"");if(!trackId)return sendJson(res,400,{ok:false,error:"trackId is required."});
 try{const ad=await cyaniteGraphQL(ANALYSIS_QUERY,{trackId}),track=ad?.libraryTrack;if(!track||track.__typename==="LibraryTrackNotFoundError")return sendJson(res,404,{ok:false,error:track?.message||"Cyanite track not found."});const a=track.audioAnalysisV7;if(a?.__typename==="AudioAnalysisV7Failed")return sendJson(res,200,{ok:true,state:"failed",trackId,error:a?.error?.message||"Cyanite analysis failed."});if(a?.__typename!=="AudioAnalysisV7Finished")return sendJson(res,200,{ok:true,state:"analyzing",trackId,title:track.title||"",analysisState:a?.__typename||"pending"});
 const dna=makeDNA(a.result),bd=await cyaniteGraphQL(SIMILAR_QUERY,{trackId}),br=bd?.libraryTrack?.similarTracks,broad=edgesOf(br);if(!broad.length)return sendJson(res,200,{ok:true,state:"searching",trackId,title:track.title||"",dna,message:br?.message||"Analysis is ready; Spotify similarity index is still preparing."});const [genreTempo,representative]=await Promise.all([safe(FILTERED_SIMILAR_QUERY,trackId),safe(REPRESENTATIVE_QUERY,trackId)]);const matches=rank([{edges:broad,weight:.55,label:"complete-audio"},{edges:genreTempo,weight:.25,label:"genre+tempo"},{edges:representative,weight:.20,label:"representative-segment"}],dna,{sourceTitle:track.title||"",excludeSpotifyId});
 return sendJson(res,200,{ok:true,state:"ready",trackId,title:track.title||"",dna,candidates:{complete:broad.length,genreTempo:genreTempo.length,representative:representative.length},authority:{genres:authorityGenres(dna),policy:"75% acoustic similarity + 25% genre-specific artist authority; Tier C is fallback only"},exclusions:{sourceSong:true,excludedSpotifyId:excludeSpotifyId||null},matches,scoreVersion:"FORTISSIMO Reference Match v0.4",scoreNote:"Cyanite acoustic matching is primary; established/mainstream artists in the detected genre receive authority priority. The source song is always excluded."});
 }catch(e){console.error("[reference-finder] status failed",e);return sendJson(res,e.code==="CYANITE_NOT_CONFIGURED"?503:502,{ok:false,state:"error",error:e.message||"Unable to read Cyanite analysis."});}}
