const API='https://itunes.apple.com/search';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, max-age=3600, s-maxage=86400');res.end(JSON.stringify(body))}
function clean(v,n=160){return String(v||'').trim().slice(0,n)}
function norm(v){return clean(v,240).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim()}
function scoreText(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .78;const aa=new Set(a.split(' ')),bb=b.split(' ');return bb.length?bb.filter(x=>aa.has(x)).length/bb.length:0}
const BAD_RELEASE=/\b(best of|greatest hits|greatest|anthology|collection|collections|essentials|ultimate|gold|hits|live)\b/i;
const ALT=/\b(live|acoustic|remix|instrumental|karaoke|sped up|slowed)\b/i;
function artwork(url){url=String(url||'').replace(/^http:/i,'https:');return url.replace(/\/100x100bb\.(jpg|png)$/i,'/600x600bb.$1')}
function rank(x,artist,title){let s=0;s+=scoreText(x.trackName,title)*55;s+=scoreText(x.artistName,artist)*35;if(!BAD_RELEASE.test(x.collectionName||''))s+=8;if(ALT.test(x.trackName||'')&&!ALT.test(title))s-=45;const year=Number(String(x.releaseDate||'').slice(0,4));if(year>1900)s+=2;return s}
export default async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return json(res,405,{ok:false,error:'Método no permitido.'})}try{const artist=clean(req.query?.artist),title=clean(req.query?.title);if(!artist||!title)return json(res,400,{ok:false,error:'Faltan artista o canción.'});const term=encodeURIComponent(`${artist} ${title}`);const r=await fetch(`${API}?term=${term}&entity=song&limit=30&country=US`,{signal:AbortSignal.timeout(12000)});const p=await r.json().catch(()=>null);if(!r.ok||!p)return json(res,502,{ok:false,error:'El catálogo musical no respondió correctamente.'});const rows=(p.results||[]).filter(x=>x.wrapperType==='track'&&x.kind==='song'&&!BAD_RELEASE.test(x.collectionName||'')).map(x=>({x,s:rank(x,artist,title)})).filter(y=>y.s>=82).sort((a,b)=>{const ay=Number(String(a.x.releaseDate||'9999').slice(0,4)),by=Number(String(b.x.releaseDate||'9999').slice(0,4));return b.s-a.s||ay-by});const best=rows[0]?.x;if(!best)return json(res,404,{ok:false,verified:false,error:'No encontramos una coincidencia segura en el catálogo musical.'});return json(res,200,{ok:true,verified:true,source:'apple',track:{title:best.trackName||title,artist:best.artistName||artist,artwork:artwork(best.artworkUrl100),release:{id:String(best.collectionId||''),title:best.collectionName||'',date:best.releaseDate||'',country:'US',artwork:artwork(best.artworkUrl100),match:'catalog-track'},trackId:String(best.trackId||''),catalogUrl:best.trackViewUrl||'',youtubeUrl:'',videoId:'',channelTitle:'',officialSignals:{topic:false,providedBy:false,vevo:false}}})}catch(e){console.error('[apple-release]',e?.message||e);return json(res,500,{ok:false,error:'No pudimos verificar esta canción en el catálogo musical.'})}}
