const GATEWAY_URL="https://ai-gateway.vercel.sh/v1/chat/completions";
const MODEL="inclusionai/ling-3.0-flash-fin-free";
const STAGE_COUNT=6;
const INSTRUMENTS=["Guitarra eléctrica","Bajo eléctrico","Guitarra acústica","Voz","Piano / Keys","Otro"];
const LEVELS=["Sin repertorio","Repertorio en desarrollo","Repertorio establecido"];
const JOURNEYS=["Aprender fundamentos primero","Ruta más rápida al estilo final","Llenar vacíos musicales","Construir repertorio profesional"];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function sendJson(res,status,body){res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(body))}
function text(v,m=500){return typeof v==="string"?v.trim().slice(0,m):""}
function clean(v,m=500){return text(v,m).replace(/[<>]/g,"")}
function arr(v,max=6,len=260){return Array.isArray(v)?v.slice(0,max).map(x=>clean(x,len)).filter(Boolean):[]}
function fail(message,status=400,extra={}){const e=new Error(message);e.status=status;Object.assign(e,extra);throw e}
function parseBody(req){if(typeof req.body==="string")return JSON.parse(req.body||"{}");return req.body||{}}
function knownLines(v){return clean(v,1200).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,12)}
function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function knownMatch(line,s){const l=norm(line),a=norm(s?.artist),t=norm(s?.title);return !!t&&(l.includes(t)||t.includes(l))&&(!a||l.includes(a)||a.split(" ").some(x=>x.length>3&&l.includes(x)))}
function extractJson(raw){let s=String(raw||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<=a)throw new SyntaxError("No JSON");let c=s.slice(a,b+1).replace(/[\u0000-\u001F]+/g," ").replace(/,\s*([}\]])/g,"$1");return JSON.parse(c)}
async function askOnce(token,system,user,timeout=42000){const r=await fetch(GATEWAY_URL,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,stream:false,messages:[{role:"system",content:system},{role:"user",content:user}]}),signal:AbortSignal.timeout(timeout)});const p=await r.json().catch(()=>null);if(!r.ok){const msg=p?.error?.message||p?.error?.code||"unknown";console.error("[study-path-ai] gateway",r.status,msg);if(r.status===429){const retryAfter=Math.max(20,Number(r.headers.get("retry-after"))||45);fail("El modelo gratuito alcanzó su límite temporal.",429,{retryAfter})}if(r.status===403||r.status===404)fail("El modelo gratuito no está disponible temporalmente.",503);fail("No pudimos generar este bloque ahora mismo.",502)}const content=p?.choices?.[0]?.message?.content;if(!content)fail("La IA no devolvió una respuesta.",502);return extractJson(content)}
async function ask(token,system,user){let last;for(let attempt=1;attempt<=2;attempt++){try{return await askOnce(token,system,user+(attempt===2?"\nREINTENTO: devuelve solamente JSON válido y completo, sin markdown ni comentarios.":""))}catch(e){last=e;if(e?.status===429||e?.status===503)throw e;const retryable=e instanceof SyntaxError||e?.name==="TimeoutError"||e?.status===502;if(!retryable||attempt===2)throw e;await sleep(1200)}}throw last}
function systemPrompt(){return`Eres el diseñador pedagógico de Study Paths de FORTISSIMO. Responde en español y SOLO JSON válido. Study Paths es un mapa curricular de repertorio. Cada etapa usa Song A → Song B: A enseña raíz, lenguaje o fundamento y B muestra evolución/aplicación hacia el destino. Usa únicamente canciones reales de alta confianza y relevantes para el instrumento. No inventes ni repitas canciones. Las canciones conocidas del alumno son obligatorias exactamente una vez. El nivel significa familiaridad con repertorio, no destreza física.`}
function normalizeMapStage(s,index){const a={artist:clean(s?.a?.artist,90),title:clean(s?.a?.title,100)},b={artist:clean(s?.b?.artist,90),title:clean(s?.b?.title,100)};if(!a.artist||!a.title||!b.artist||!b.title)fail("La IA dejó incompleta una canción.",502);return{index,title:clean(s?.title,90),objective:clean(s?.objective,280),a,b,connection:clean(s?.connection,360)}}
function validateMap(map,known){if(!map||!Array.isArray(map.stages)||map.stages.length!==STAGE_COUNT)fail("La IA devolvió un mapa incompleto.",502);const used=new Set();for(const s of map.stages)for(const z of[s.a,s.b]){const k=`${norm(z.artist)}::${norm(z.title)}`;if(used.has(k))fail("La IA repitió una canción.",502);used.add(k)}const songs=map.stages.flatMap(s=>[s.a,s.b]);for(const line of known)if(!songs.some(s=>knownMatch(line,s)))fail(`La IA omitió una canción obligatoria: ${line}.`,502);return map}
function toneIntel(t,instrument){const arch=instrument==="Guitarra eléctrica"&&["Cory Wong","Petrucci"].includes(clean(t?.archetype,40))?clean(t.archetype,40):"";return{status:"≈ Aproximación tonal",target:clean(t?.target,260),guitar:clean(t?.guitar,220),amp:clean(t?.amp,220),fx:clean(t?.fx,220),feel:clean(t?.feel,260),archetype:arch,recipe:arr(t?.recipe,6,220),listen:clean(t?.listen,300)}}
function enrichSong(base,s,instrument){return{artist:base.artist,title:base.title,study:clean(s?.study,320),listen:arr(s?.listen,4,260),tone:{character:clean(s?.tone?.character,180),amp:clean(s?.tone?.amp,180),feel:clean(s?.tone?.feel,240)},mastery:arr(s?.mastery,4,260),toneIntelligence:toneIntel(s?.toneIntelligence,instrument)}}
function normalizeDetail(ms,d,instrument){const a=enrichSong(ms.a,d?.a,instrument),b=enrichSong(ms.b,d?.b,instrument);const out={id:`ai-stage-${Date.now()}-${ms.index}`,title:ms.title,objective:ms.objective,lessonWhy:clean(d?.lessonWhy,420),skills:arr(d?.skills,6,80),a,b,connection:ms.connection,bridge:arr(d?.bridge,4,280)};for(const z of[a,b])if(!z.study||z.listen.length<3||z.mastery.length<3||!z.tone.character||!z.tone.amp||!z.tone.feel||!z.toneIntelligence.target||!z.toneIntelligence.amp||!z.toneIntelligence.feel||z.toneIntelligence.recipe.length<4)fail("La IA devolvió una mini-lección incompleta.",502);if(!out.lessonWhy||out.skills.length<3||out.bridge.length<3)fail("La IA devolvió una etapa incompleta.",502);return out}
function detailPrompt(instrument,stages){return`Completa SOLO estas ${stages.length} etapas ya decididas. NO cambies artistas, títulos, orden ni A/B.\n${stages.map(s=>`ETAPA ${s.index}: ${s.title}\nObjetivo: ${s.objective}\nA: ${s.a.artist} — ${s.a.title}\nB: ${s.b.artist} — ${s.b.title}\nConexión: ${s.connection}`).join("\n\n")}\nDevuelve {"stages":[...]}. Cada objeto debe incluir: index, lessonWhy, skills[3-5], a y b con study, listen[3], tone{character,amp,feel}, mastery[3], toneIntelligence{target,guitar,amp,fx,feel,archetype,recipe[4],listen}, y bridge[3]. Tone Intelligence siempre es aproximación sonora. Para guitarra eléctrica archetype solo puede ser Cory Wong o Petrucci; para otros instrumentos usa cadena vacía.`}
export default async function handler(req,res){if(req.method!=="POST"){res.setHeader("Allow","POST");return sendJson(res,405,{ok:false,error:"Método no permitido."})}try{const b=parseBody(req),phase=text(b.phase,20)||"mapChunk",instrument=text(b.instrument,60),level=text(b.level,60),objective=clean(b.objective,220),destination=clean(b.destination,140),preferences=clean(b.preferences,500),journey=text(b.journey,80),known=knownLines(b.knownSongs),stageCount=Number(b.stageCount);if(!INSTRUMENTS.includes(instrument)||!LEVELS.includes(level)||!objective||!destination||!JOURNEYS.includes(journey)||stageCount!==STAGE_COUNT)fail("El AI Builder gratuito usa una ruta estable de 6 etapas.");if(known.length>12)fail("La ruta de 6 etapas admite hasta 12 canciones conocidas obligatorias.");const token=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;if(!token)fail("La conexión de IA todavía no está disponible.",503);
if(phase==="mapChunk"){const start=Number(b.start)||0;if(![0,2,4].includes(start))fail("Bloque de mapa inválido.");const previous=Array.isArray(b.previousStages)?b.previousStages:[],count=2,used=previous.flatMap(s=>[`${s.a?.artist} — ${s.a?.title}`,`${s.b?.artist} — ${s.b?.title}`]).filter(Boolean),remaining=known.filter(line=>!previous.some(s=>knownMatch(line,s.a)||knownMatch(line,s.b))),mustNow=start===4?remaining:remaining.slice(0,Math.min(remaining.length,4));const user=`RESPUESTAS DEL ALUMNO\nInstrumento: ${instrument}\nNivel: ${level}\nObjetivo: ${objective}\nDestino: ${destination}\nPreferencias: ${preferences||"Sin preferencias adicionales"}\nRecorrido: ${journey}\nRuta total: 6 etapas / 12 canciones.\nGenera SOLO etapas ${start+1}-${start+2}.\nCanciones ya usadas, NO repetir: ${used.join(" | ")||"ninguna"}.\nCanciones conocidas obligatorias que deben aparecer en ESTE bloque: ${mustNow.join(" | ")||"ninguna"}.\nCanciones conocidas aún pendientes después de este bloque: ${remaining.filter(x=>!mustNow.includes(x)).join(" | ")||"ninguna"}.\n${previous.length?`Contexto previo: ${previous.slice(-2).map(s=>`Etapa ${s.index}: ${s.title}`).join("; ")}.`:"Este es el inicio de la ruta."}\nDevuelve SOLO {"name":"...","objective":"...","stages":[{"title":"...","objective":"...","a":{"artist":"...","title":"..."},"b":{"artist":"...","title":"..."},"connection":"transferencia concreta A→B"},{...}]}. Deben ser exactamente 2 etapas.`;const raw=await ask(token,systemPrompt(),user);if(!Array.isArray(raw?.stages)||raw.stages.length!==2)fail("La IA devolvió un bloque de mapa incompleto.",502);const stages=raw.stages.map((s,i)=>normalizeMapStage(s,start+i+1)),all=[...previous,...stages],seen=new Set();for(const s of all)for(const z of[s.a,s.b]){const k=`${norm(z.artist)}::${norm(z.title)}`;if(seen.has(k))fail("La IA repitió una canción.",502);seen.add(k)}for(const line of mustNow)if(!stages.some(s=>knownMatch(line,s.a)||knownMatch(line,s.b)))fail(`La IA omitió una canción obligatoria en este bloque: ${line}.`,502);return sendJson(res,200,{ok:true,phase:"mapChunk",start,name:clean(raw.name,70)||clean(b.mapName,70)||`Ruta hacia ${destination}`,objective:clean(raw.objective,320)||clean(b.mapObjective,320)||objective,stages,modelTier:"free"})}
if(phase==="validateMap"){const map={name:clean(b.map?.name,70),objective:clean(b.map?.objective,320),stages:(b.map?.stages||[]).map((s,i)=>normalizeMapStage(s,i+1))};return sendJson(res,200,{ok:true,phase:"validateMap",map:validateMap(map,known)})}
if(phase==="detail"){const map=b.map;if(!map||!Array.isArray(map.stages)||map.stages.length!==STAGE_COUNT)fail("Falta el mapa de la ruta.");const start=Number(b.start);if(![0,2,4].includes(start))fail("Bloque de lección inválido.");const chunk=map.stages.slice(start,start+2),raw=await ask(token,systemPrompt(),detailPrompt(instrument,chunk));if(!Array.isArray(raw?.stages)||raw.stages.length!==2)fail("La IA devolvió un bloque incompleto.",502);return sendJson(res,200,{ok:true,phase:"detail",start,stages:chunk.map((s,i)=>normalizeDetail(s,raw.stages[i],instrument)),modelTier:"free"})}fail("Fase de generación inválida.");}catch(e){if(e?.status===429)return sendJson(res,429,{ok:false,error:"El modelo gratuito alcanzó su límite temporal. FORTISSIMO conservará tu progreso y continuará cuando vuelva a estar disponible.",retryAfter:e.retryAfter||45,code:"FREE_RATE_LIMIT"});if(e?.name==="TimeoutError")return sendJson(res,504,{ok:false,error:"La IA gratuita tardó demasiado en este bloque. Inténtalo otra vez."});if(e instanceof SyntaxError)return sendJson(res,502,{ok:false,error:"La IA respondió en un formato inesperado. Inténtalo otra vez."});console.error("[study-path-ai] generation failed",e?.message||e);return sendJson(res,e?.status||500,{ok:false,error:e?.status?e.message:"No pudimos generar la ruta ahora mismo."})}}