const GATEWAY_URL="https://ai-gateway.vercel.sh/v1/chat/completions";
const MODEL="inclusionai/ling-3.0-flash-fin-free";
const STAGE_COUNT=6;
const INSTRUMENTS=["Guitarra eléctrica","Bajo eléctrico","Guitarra acústica","Voz","Piano / Keys","Otro"];
const LEVELS=["Sin repertorio","Repertorio en desarrollo","Repertorio establecido"];
const JOURNEYS=["Aprender fundamentos primero","Ruta más rápida al estilo final","Llenar vacíos musicales","Construir repertorio profesional"];
function send(res,status,body){res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(body))}
function txt(v,n=500){return typeof v==="string"?v.trim().slice(0,n):""}
function clean(v,n=500){return txt(v,n).replace(/[<>]/g,"")}
function arr(v,max=6,n=260){return Array.isArray(v)?v.slice(0,max).map(x=>clean(x,n)).filter(Boolean):[]}
function fail(message,status=400,extra={}){const e=new Error(message);e.status=status;Object.assign(e,extra);throw e}
function body(req){if(typeof req.body==="string")return JSON.parse(req.body||"{}");return req.body||{}}
function known(v){return clean(v,1200).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,12)}
function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function match(line,s){const l=norm(line),a=norm(s?.artist),t=norm(s?.title);return !!t&&(l.includes(t)||t.includes(l))&&(!a||l.includes(a)||a.split(" ").some(x=>x.length>3&&l.includes(x)))}
function extract(raw){let s=String(raw||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<=a)throw new SyntaxError("No JSON");let c=s.slice(a,b+1).replace(/[\u0000-\u001F]+/g," ").replace(/,\s*([}\]])/g,"$1");return JSON.parse(c)}
async function ask(token,system,user,maxTokens,timeout=36000){const r=await fetch(GATEWAY_URL,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,stream:false,max_tokens:maxTokens,messages:[{role:"system",content:system},{role:"user",content:user}]}),signal:AbortSignal.timeout(timeout)});const p=await r.json().catch(()=>null);if(!r.ok){const msg=p?.error?.message||p?.error?.code||"unknown";console.error("[study-path-stage-ai] gateway",r.status,msg);if(r.status===429){const retryAfter=Math.max(30,Number(r.headers.get("retry-after"))||45);fail("El modelo gratuito alcanzó su límite temporal.",429,{retryAfter})}if(r.status===403||r.status===404)fail("El modelo gratuito no está disponible temporalmente.",503);fail("No pudimos generar esta etapa ahora mismo.",502)}const content=p?.choices?.[0]?.message?.content;if(!content)fail("La IA no devolvió una respuesta.",502);return extract(content)}
function systemPrompt(){return`Eres el diseñador pedagógico de Study Paths de FORTISSIMO. Responde en español y SOLO JSON válido, sin markdown. Diseñas una ruta compacta de 6 etapas / 12 canciones que debe conservar la profundidad de un recorrido largo. Cada etapa es un capítulo esencial de evolución musical y usa Song A → Song B: A enseña raíz, fundamento o antecedente; B demuestra evolución, aplicación posterior o acercamiento al destino. La conexión A→B debe explicar transferencia concreta de groove, armonía, fraseo, articulación, arreglo o criterio sonoro. Usa solo canciones reales de alta confianza, sin inventar ni repetir. Las canciones conocidas del alumno son obligatorias exactamente una vez. El nivel significa familiaridad con repertorio, no dificultad técnica. Study Paths es un mapa curricular, no incluye tabs, stems, player ni metrónomo.`}
const chapters={1:"Raíces/fundamentos auténticos del lenguaje que alimenta el destino.",2:"Groove y función rítmica: cómo el instrumento ocupa espacio y construye pocket.",3:"Armonía, voicings o vocabulario melódico equivalente que expande el lenguaje.",4:"Articulación, dinámica, sonido y función dentro del arreglo.",5:"Transición histórica decisiva: el lenguaje empieza a parecerse claramente al estilo destino.",6:"Llegada: repertorio moderno/profesional de referencia que representa muy bien el destino actual."};
function mapStage(s,index){const a={artist:clean(s?.a?.artist,90),title:clean(s?.a?.title,100)},b={artist:clean(s?.b?.artist,90),title:clean(s?.b?.title,100)};if(!a.artist||!a.title||!b.artist||!b.title||!clean(s?.title,90)||!clean(s?.objective,280)||!clean(s?.connection,360))fail("La IA devolvió una etapa incompleta.",502);return{index,title:clean(s.title,90),objective:clean(s.objective,280),a,b,connection:clean(s.connection,360)}}
function tone(t,instrument){const ar=instrument==="Guitarra eléctrica"&&["Cory Wong","Petrucci"].includes(clean(t?.archetype,40))?clean(t.archetype,40):"";return{status:"≈ Aproximación tonal",target:clean(t?.target,240),guitar:clean(t?.guitar,180),amp:clean(t?.amp,180),fx:clean(t?.fx,180),feel:clean(t?.feel,220),archetype:ar,recipe:arr(t?.recipe,5,180),listen:clean(t?.listen,240)}}
function song(base,s,instrument){return{artist:base.artist,title:base.title,study:clean(s?.study,280),listen:arr(s?.listen,3,220),tone:{character:clean(s?.tone?.character,160),amp:clean(s?.tone?.amp,160),feel:clean(s?.tone?.feel,200)},mastery:arr(s?.mastery,3,220),toneIntelligence:tone(s?.toneIntelligence,instrument)}}
function detail(ms,d,instrument){const a=song(ms.a,d?.a,instrument),b=song(ms.b,d?.b,instrument),out={id:`ai-stage-${Date.now()}-${ms.index}`,title:ms.title,objective:ms.objective,lessonWhy:clean(d?.lessonWhy,360),skills:arr(d?.skills,5,70),a,b,connection:ms.connection,bridge:arr(d?.bridge,3,240)};for(const z of[a,b])if(!z.study||z.listen.length<2||z.mastery.length<2||!z.tone.character||!z.tone.amp||!z.tone.feel||!z.toneIntelligence.target||!z.toneIntelligence.amp||!z.toneIntelligence.feel||z.toneIntelligence.recipe.length<3)fail("La IA devolvió una mini-lección incompleta.",502);if(!out.lessonWhy||out.skills.length<2||out.bridge.length<2)fail("La IA devolvió una etapa incompleta.",502);return out}
export default async function handler(req,res){if(req.method!=="POST"){res.setHeader("Allow","POST");return send(res,405,{ok:false,error:"Método no permitido."})}try{const b=body(req),phase=txt(b.phase,20),instrument=txt(b.instrument,60),level=txt(b.level,60),objective=clean(b.objective,220),destination=clean(b.destination,140),preferences=clean(b.preferences,500),journey=txt(b.journey,80),knownSongs=known(b.knownSongs),stageCount=Number(b.stageCount),index=Number(b.index);if(!INSTRUMENTS.includes(instrument)||!LEVELS.includes(level)||!objective||!destination||!JOURNEYS.includes(journey)||stageCount!==STAGE_COUNT)fail("El AI Builder gratuito usa una ruta estable de 6 etapas.");if(!Number.isInteger(index)||index<1||index>6)fail("Etapa inválida.");const token=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;if(!token)fail("La conexión de IA todavía no está disponible.",503);
if(phase==="mapStage"){const previous=Array.isArray(b.previousStages)?b.previousStages:[],used=previous.flatMap(s=>[`${s.a?.artist} — ${s.a?.title}`,`${s.b?.artist} — ${s.b?.title}`]).filter(Boolean),remaining=knownSongs.filter(line=>!previous.some(s=>match(line,s.a)||match(line,s.b))),remainingStages=7-index,minMust=Math.max(0,remaining.length-(remainingStages*2)),mustNow=remaining.slice(0,Math.min(2,minMust));const user=`Instrumento: ${instrument}\nNivel de repertorio: ${level}\nObjetivo: ${objective}\nDestino: ${destination}\nPreferencias: ${preferences||"Sin preferencias adicionales"}\nTipo de viaje: ${journey}\nRuta total: 6 etapas / 12 canciones.\nGenera SOLO la ETAPA ${index}. Función pedagógica del capítulo: ${chapters[index]}\nCanciones ya usadas, prohibido repetir: ${used.join(" | ")||"ninguna"}.\nCanciones conocidas obligatorias que DEBEN entrar ahora por capacidad: ${mustNow.join(" | ")||"ninguna"}.\nCanciones conocidas pendientes que PUEDES usar ahora si encajan pedagógicamente: ${remaining.filter(x=>!mustNow.includes(x)).join(" | ")||"ninguna"}.\nContexto previo: ${previous.length?previous.slice(-2).map(s=>`Etapa ${s.index}: ${s.title}; A ${s.a?.artist} — ${s.a?.title}; B ${s.b?.artist} — ${s.b?.title}`).join(" | "):"inicio de la genealogía"}.\nNo elijas por popularidad: el instrumento debe tener material útil. La etapa ${index===6?"DEBE terminar en referencias modernas/profesionales fuertes del estilo destino":"debe avanzar claramente hacia la siguiente"}. Devuelve SOLO {"name":"nombre de ruta","objective":"objetivo curricular","stage":{"title":"...","objective":"...","a":{"artist":"...","title":"..."},"b":{"artist":"...","title":"..."},"connection":"transferencia musical concreta A→B"}}.`;const raw=await ask(token,systemPrompt(),user,1000);const stage=mapStage(raw?.stage,index);const all=[...previous,stage],seen=new Set();for(const st of all)for(const z of[st.a,st.b]){const k=`${norm(z.artist)}::${norm(z.title)}`;if(seen.has(k))fail("La IA repitió una canción.",502);seen.add(k)}for(const line of mustNow)if(!match(line,stage.a)&&!match(line,stage.b))fail(`La IA omitió una canción obligatoria en esta etapa: ${line}.`,502);if(index===6){for(const line of remaining)if(!match(line,stage.a)&&!match(line,stage.b)&&!previous.some(s=>match(line,s.a)||match(line,s.b)))fail(`La IA omitió una canción obligatoria: ${line}.`,502)}return send(res,200,{ok:true,phase,name:clean(raw?.name,70)||clean(b.mapName,70)||`Ruta hacia ${destination}`,objective:clean(raw?.objective,320)||clean(b.mapObjective,320)||objective,stage,modelTier:"free"})}
if(phase==="detailStage"){const ms=b.stage;if(!ms||Number(ms.index)!==index)fail("Falta el mapa de esta etapa.");const user=`Completa SOLO la mini-lección de la ETAPA ${index}. No cambies artista, canción, orden ni pareja A/B.\nEtapa: ${ms.title}\nObjetivo: ${ms.objective}\nA: ${ms.a?.artist} — ${ms.a?.title}\nB: ${ms.b?.artist} — ${ms.b?.title}\nConexión A→B: ${ms.connection}\nExtrae máximo valor pedagógico: qué estudiar en la parte del instrumento, qué escuchar, función en arreglo, articulación/dinámica/sonido, criterio de dominio y qué se transfiere de A a B. Tone Intelligence siempre es aproximación, nunca afirmes equipo histórico. Para guitarra eléctrica archetype solo Cory Wong o Petrucci; otros instrumentos cadena vacía. Devuelve SOLO {"stage":{"lessonWhy":"...","skills":[3-5],"a":{"study":"...","listen":[3],"tone":{"character":"...","amp":"...","feel":"..."},"mastery":[3],"toneIntelligence":{"target":"...","guitar":"...","amp":"...","fx":"...","feel":"...","archetype":"...","recipe":[3-5],"listen":"..."}},"b":{MISMAS CLAVES},"bridge":[3]}}.`;const raw=await ask(token,systemPrompt(),user,2200);return send(res,200,{ok:true,phase,stage:detail(ms,raw?.stage,instrument),modelTier:"free"})}
fail("Fase inválida.");}catch(e){if(e?.status===429)return send(res,429,{ok:false,error:"El modelo gratuito alcanzó su límite temporal. Tu progreso está guardado.",retryAfter:e.retryAfter||45,code:"FREE_RATE_LIMIT"});if(e?.name==="TimeoutError")return send(res,504,{ok:false,error:"Esta etapa tardó demasiado. Tu progreso está guardado; puedes continuar desde aquí.",code:"STAGE_TIMEOUT"});if(e instanceof SyntaxError)return send(res,502,{ok:false,error:"La IA respondió en un formato inesperado. Tu progreso está guardado; reintentaremos solo esta etapa.",code:"BAD_JSON"});console.error("[study-path-stage-ai] failed",e?.message||e);return send(res,e?.status||500,{ok:false,error:e?.status?e.message:"No pudimos generar esta etapa ahora mismo."})}}