const TOKEN_URL="https://accounts.spotify.com/api/token";
const API="https://api.spotify.com/v1";
let cached={token:"",expires:0};
function json(res,status,body){res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","public, max-age=3600, s-maxage=86400");res.end(JSON.stringify(body))}
function clean(v,n=140){return String(v||"").trim().slice(0,n)}
function norm(v){return clean(v,200).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function score(item,artist,title){const t=norm(item?.name),wantT=norm(title),artists=(item?.artists||[]).map(a=>norm(a.name));let s=0;if(t===wantT)s+=70;else if(t.includes(wantT)||wantT.includes(t))s+=40;if(artists.some(a=>a===norm(artist)))s+=30;else if(artists.some(a=>a.includes(norm(artist))||norm(artist).includes(a)))s+=18;return s}
async function token(){if(cached.token&&Date.now()<cached.expires)return cached.token;const id=process.env.SPOTIFY_CLIENT_ID,secret=process.env.SPOTIFY_CLIENT_SECRET;if(!id||!secret)throw Object.assign(new Error("Spotify no está configurado en el servidor."),{status:503,code:"SPOTIFY_NOT_CONFIGURED"});const r=await fetch(TOKEN_URL,{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials",signal:AbortSignal.timeout(10000)});const p=await r.json().catch(()=>null);if(!r.ok||!p?.access_token)throw Object.assign(new Error("No se pudo autenticar Spotify."),{status:502});cached={token:p.access_token,expires:Date.now()+Math.max(30,(p.expires_in||3600)-60)*1000};return cached.token}
export default async function handler(req,res){if(req.method!=="GET"){res.setHeader("Allow","GET");return json(res,405,{ok:false,error:"Método no permitido."})}try{const artist=clean(req.query?.artist),title=clean(req.query?.title);if(!artist||!title)return json(res,400,{ok:false,error:"Faltan artista o canción."});const access=await token();const q=encodeURIComponent(`track:${title} artist:${artist}`);const r=await fetch(`${API}/search?q=${q}&type=track&limit=5`,{headers:{Authorization:`Bearer ${access}`},signal:AbortSignal.timeout(10000)});const p=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error("Spotify no respondió correctamente."),{status:r.status===429?429:502});const ranked=(p?.tracks?.items||[]).map(x=>({x,s:score(x,artist,title)})).sort((a,b)=>b.s-a.s);const best=ranked[0];if(!best||best.s<70)return json(res,404,{ok:false,verified:false,error:"No encontramos una coincidencia suficientemente segura en Spotify."});const x=best.x,images=x.album?.images||[];return json(res,200,{ok:true,verified:true,track:{id:x.id,uri:x.uri,title:x.name,artists:(x.artists||[]).map(a=>a.name),album:x.album?.name||"",artwork:images[0]?.url||"",artworkSmall:images.find(i=>i.width<=300)?.url||images[images.length-1]?.url||images[0]?.url||"",spotifyUrl:x.external_urls?.spotify||""},matchScore:best.s})}catch(e){console.error("[spotify-track]",e?.code||e?.message||e);return json(res,e?.status||500,{ok:false,code:e?.code||null,error:e?.message||"No pudimos verificar esta canción en Spotify."})}}
