const YT='https://www.googleapis.com/youtube/v3';
const MB='https://musicbrainz.org/ws/2';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, max-age=3600, s-maxage=86400');res.end(JSON.stringify(body))}
function clean(v,n=160){return String(v||'').trim().slice(0,n)}
function norm(v){return clean(v,240).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim()}
function textScore(hay,needle){const a=norm(hay),b=norm(needle);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .76;const aa=new Set(a.split(' ')),bb=b.split(' ');return bb.length?bb.filter(x=>aa.has(x)).length/bb.length:0}
function ytScore(item,artist,title){const s=item.snippet||{},channel=s.channelTitle||'',desc=s.description||'',videoTitle=s.title||'';let score=0;score+=Math.round(textScore(videoTitle,title)*50);score+=Math.round(textScore(videoTitle,artist)*22);score+=Math.round(textScore(channel,artist)*13);if(/- topic$/i.test(channel))score+=12;if(/provided to youtube by/i.test(desc))score+=18;if(/official audio|official music video|audio/i.test(videoTitle))score+=5;if(/cover|karaoke|reaction|tutorial|lesson|live cover/i.test(videoTitle))score-=35;return score}
async function youtube(artist,title,key){const q=encodeURIComponent(`${artist} ${title}`);const sr=await fetch(`${YT}/search?part=snippet&type=video&videoCategoryId=10&maxResults=10&q=${q}&key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout(12000)});const sp=await sr.json().catch(()=>null);if(!sr.ok)throw Object.assign(new Error(sp?.error?.message||'YouTube no respondió correctamente.'),{status:sr.status===403?403:502,code:'YOUTUBE_SEARCH_FAILED'});const ids=(sp?.items||[]).map(x=>x.id?.videoId).filter(Boolean);if(!ids.length)return null;const vr=await fetch(`${YT}/videos?part=snippet,contentDetails&id=${ids.join(',')}&key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout(12000)});const vp=await vr.json().catch(()=>null);if(!vr.ok)throw Object.assign(new Error(vp?.error?.message||'No pudimos leer los resultados de YouTube.'),{status:502});const ranked=(vp?.items||[]).map(x=>({x,s:ytScore(x,artist,title)})).sort((a,b)=>b.s-a.s);const best=ranked[0];if(!best||best.s<58)return null;const s=best.x.snippet||{};return{videoId:best.x.id,title:s.title||title,channelTitle:s.channelTitle||'',channelId:s.channelId||'',publishedAt:s.publishedAt||'',description:s.description||'',thumbnail:s.thumbnails?.maxres?.url||s.thumbnails?.standard?.url||s.thumbnails?.high?.url||s.thumbnails?.medium?.url||s.thumbnails?.default?.url||'',youtubeUrl:`https://www.youtube.com/watch?v=${best.x.id}`,matchScore:best.s,officialSignals:{topic:/- topic$/i.test(s.channelTitle||''),providedBy:/provided to youtube by/i.test(s.description||'')}}}
async function musicbrainz(artist,title){const query=encodeURIComponent(`recording:"${title.replace(/"/g,'')}" AND artist:"${artist.replace(/"/g,'')}"`);const r=await fetch(`${MB}/recording/?query=${query}&fmt=json&limit=8`,{headers:{'User-Agent':'FORTISSIMO/1.0 (https://fortegym.vercel.app)'},signal:AbortSignal.timeout(12000)});if(!r.ok)return null;const p=await r.json().catch(()=>null),rows=p?.recordings||[];const ranked=rows.map(x=>{let s=0;s+=textScore(x.title,title)*55;s+=Math.max(0,...(x['artist-credit']||[]).map(a=>textScore(a?.name||a?.artist?.name,artist)))*35;s+=Math.min(10,Number(x.score||0)/10);return{x,s}}).sort((a,b)=>b.s-a.s);const rec=ranked[0]?.x;if(!rec||ranked[0].s<72)return null;const releases=(rec.releases||[]).filter(x=>x.status==='Official'||!x.status).sort((a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999')));const preferred=releases.find(x=>!((x['release-group']?.['secondary-types']||[]).includes('Compilation')))||releases[0]||null;if(!preferred)return{recordingId:rec.id,release:null};const rg=preferred['release-group']?.id||'';let artwork='';if(rg){const ca=await fetch(`https://coverartarchive.org/release-group/${rg}`,{headers:{'User-Agent':'FORTISSIMO/1.0'},signal:AbortSignal.timeout(10000)}).catch(()=>null);if(ca?.ok){const cp=await ca.json().catch(()=>null);const front=(cp?.images||[]).find(i=>i.front)||(cp?.images||[])[0];artwork=front?.thumbnails?.['500']||front?.thumbnails?.large||front?.image||''}}
return{recordingId:rec.id,release:{id:preferred.id,title:preferred.title||'',date:preferred.date||'',country:preferred.country||'',releaseGroupId:rg,artwork}}}
export default async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return json(res,405,{ok:false,error:'Método no permitido.'})}try{const artist=clean(req.query?.artist),title=clean(req.query?.title),key=process.env.YOUTUBE_API_KEY;if(!artist||!title)return json(res,400,{ok:false,error:'Faltan artista o canción.'});if(!key)return json(res,503,{ok:false,code:'YOUTUBE_NOT_CONFIGURED',error:'YouTube Data API no está configurada en el servidor.'});const yt=await youtube(artist,title,key);if(!yt)return json(res,404,{ok:false,verified:false,error:'No encontramos una coincidencia suficientemente segura en YouTube.'});const mb=await musicbrainz(artist,title).catch(()=>null);const artwork=mb?.release?.artwork||yt.thumbnail||'';return json(res,200,{ok:true,verified:true,source:'youtube',track:{title,artist,videoTitle:yt.title,channelTitle:yt.channelTitle,channelId:yt.channelId,videoId:yt.videoId,youtubeUrl:yt.youtubeUrl,thumbnail:yt.thumbnail,artwork,release:mb?.release||null,recordingId:mb?.recordingId||'',officialSignals:yt.officialSignals},matchScore:yt.matchScore})}catch(e){console.error('[youtube-release]',e?.code||e?.message||e);return json(res,e?.status||500,{ok:false,code:e?.code||null,error:e?.message||'No pudimos verificar esta canción.'})}}
