import assert from 'node:assert/strict';import fs from 'node:fs';
const base=fs.readFileSync(new URL('../assets/vibe-roulette-composer-mode-v1.js',import.meta.url),'utf8');
const polish=fs.readFileSync(new URL('../assets/vibe-roulette-composer-polish-v14-1b.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../assets/vibe-roulette-spin-audio-sync-v1.js',import.meta.url),'utf8');
for(const token of ["version:'14.0.0'","pillars:Object.freeze(['listen','lock','edit','variate'])",'keepDnaMaxChanges:2','window.__FORTISSIMO_VIBE_SESSION_V1__','window.__FORTISSIMO_VIBE_ENGINE__','function regenerateSlot(slotIndex)','function keepDNA()','function undo()','function redo()','SPIN AGAIN TO REPLACE','Your edited composition is protected'])assert.ok(base.includes(token),`Composer 14.0 core regression: ${token}`);
for(const token of ["version:'14.1.1'","tools:Object.freeze(['vary','edit'])",'independentPasses:true','twoChordsPerBar:true','liveHumanPianistTiming:true','composerBarEvents','annotateLiveArrangement','data-action="vary"','data-action="edit"','interceptCardTaps','auditionBar'])assert.ok(polish.includes(token),`Composer 14.1b polish missing: ${token}`);
assert.equal(polish.includes('data-action="lock"'),false,'14.1b surface must remove Lock');
assert.equal(polish.includes('data-action="listen"'),false,'14.1b surface must remove dedicated Play; tapping card auditions');
for(const token of ['composer14-1b','installComposerPolish()','1.9-phase14-1b-piano-roll-polish'])assert.ok(loader.includes(token),`Composer loader missing: ${token}`);
assert.ok(!polish.includes("require('node:"));assert.ok(!polish.includes('child_process'));assert.ok(!polish.includes('startDrag('));
console.log('PASS Composer: 14.0 learning/history remains intact while 14.1b simplifies cards and adds exact independent 1x4 or 2x2 bar composition.');
