import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const roll=fs.readFileSync(new URL('../assets/vibe-roulette-piano-roll-v1.js',import.meta.url),'utf8');
const exp=fs.readFileSync(new URL('../assets/vibe-roulette-songstarter-export-v1.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../assets/vibe-roulette-spin-audio-sync-v1.js',import.meta.url),'utf8');
const subdivision=fs.readFileSync(new URL('../assets/vibe-roulette-chord-subdivision-v1.js',import.meta.url),'utf8');
test('Phase 14.1 remains fixed to eight-bar MAIN plus TEXTURES',()=>{assert.match(roll,/version:'14\.1\.1'/);assert.match(roll,/bars:8/);assert.match(roll,/layers:Object\.freeze\(\['foundation','texture'\]\)/);assert.match(roll,/beats:32/);});
test('Piano Roll edits pitch timing duration velocity and supports selection',()=>{for(const token of ['event.startBeat=','event.midi=','durationBeats=','event.velocity=','key.toLowerCase()===\'a\'','Delete'])assert.ok(roll.includes(token),token);});
test('Piano Roll has play pause playhead zoom navigation and note audition',()=>{for(const token of ['data-play','pr-playhead','setZoom(','data-zin','data-zout','data-left','data-right','function audition(','AudioContext','Space'])assert.ok(roll.includes(token),token);});
test('selected notes are visibly highlighted',()=>{assert.match(roll,/data-selected=true/);assert.match(roll,/background:#f2f2f2/);});
test('edited plan is source for DAW MIDI',()=>{assert.match(exp,/pianoRollOverride/);assert.match(exp,/if\(pianoRollOverride\)return clone\(pianoRollOverride\)/);assert.match(exp,/Piano Roll edits/);});
test('chord labels detect whole or two-half-bar harmony',()=>{assert.match(roll,/chordName\(all,bar\*4,bar\*4\+2\)/);assert.match(roll,/chordName\(all,bar\*4\+2,bar\*4\+4\)/);assert.match(roll,/dataset\.chordSubdivision/);});
test('one or two chords per bar control is available in Edit chord sheet',()=>{for(const token of ['1 CHORD · WHOLE','2 CHORDS · HALF + HALF','splitBar','mergeBar','subdivisionClone'])assert.ok(subdivision.includes(token),token);});
test('Chorus keeps MAIN and TEXTURES editor',()=>{assert.match(roll,/CHORUS PIANO ROLL · MAIN \/ TEXTURES/);assert.match(roll,/data-layer="foundation"/);assert.match(roll,/data-layer="texture"/);});
test('runtime cache-bust loads polished Phase 14.1 and subdivision',()=>{assert.match(loader,/pianoroll14-1b/);assert.match(loader,/subdivision14-1b/);assert.match(loader,/1\.9-phase14-1b-polish/);});
