import assert from 'node:assert/strict';import fs from 'node:fs';
const base=fs.readFileSync(new URL('../assets/vibe-roulette-composer-mode-v1.js',import.meta.url),'utf8');
const polish=fs.readFileSync(new URL('../assets/vibe-roulette-composer-polish-v14-1b.js',import.meta.url),'utf8');
const loader=fs.readFileSync(new URL('../assets/vibe-roulette-spin-audio-sync-v1.js',import.meta.url),'utf8');
for(const token of ["version:'14.1.1'","pillars:Object.freeze(['listen','edit','variate'])",'keepDnaMaxChanges:2','pianoRoll:true','subdivisions:true','barExact:true','window.__FORTISSIMO_VIBE_SESSION_V1__','window.__FORTISSIMO_VIBE_ENGINE__','function regenerateSlot(slot)','function keepDNA()','function undo()','function redo()','SPIN AGAIN TO REPLACE','Your edited composition is protected','data-action="vary"','data-action="edit"'])assert.ok(base.includes(token),`Composer 14.1 core regression: ${token}`);
assert.equal(base.includes('data-action="lock"'),false,'Composer card Lock must stay removed');
assert.equal(base.includes('data-action="listen"'),false,'Dedicated card Play must stay removed; card tap auditions');
for(const token of ["version:'14.1.1'","tools:Object.freeze(['vary','edit'])",'independentPasses:true','twoChordsPerBar:true','liveHumanPianistTiming:true','composerBarEvents','annotateLiveArrangement','data-mode="whole"','data-mode="split"','2 chords · 2 + 2 beats','interceptCardTaps','auditionBar'])assert.ok(polish.includes(token),`Composer 14.1b polish missing: ${token}`);
assert.equal(polish.includes('data-action="lock"'),false);assert.equal(polish.includes('data-action="listen"'),false);
for(const token of ['composer14-1b','installComposerPolish()','1.9-phase14-1b-piano-roll-polish'])assert.ok(loader.includes(token),`Composer loader missing: ${token}`);
assert.ok(!polish.includes("require('node:"));assert.ok(!polish.includes('child_process'));assert.ok(!polish.includes('startDrag('));
console.log('PASS Composer 14.1b: tap-to-listen, exact-bar regenerate/edit, no lock/play clutter, independent A/A-prime and 1x4 or 2x2 timing.');
